import React from 'react';
import { Story, Meta } from '@storybook/react';

import { Card } from '../../components/Card/Card';
import {ICardProps} from '../../components/Card/types';

export default {
  title: 'Pluto/Card',
  component: Card,
  argTypes: {
    backgroundColor: { control: 'color' },
  },
} as Meta;

const Template: Story<ICardProps> = (args) => <Card {...args} />;

export const Main = Template.bind({});
Main.args = {
  backgroundColor: 'blue',
  repoData: {
    "id": 290171332,
    "node_id": "MDEwOlJlcG9zaXRvcnkyOTAxNzEzMzI=",
    "name": "hacker",
    "full_name": "Augani/hacker",
    "private": false,
    "owner": {
        "login": "Augani",
        "id": 13237525,
        "node_id": "MDQ6VXNlcjEzMjM3NTI1",
        "avatar_url": "https://avatars.githubusercontent.com/u/13237525?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Augani",
        "html_url": "https://github.com/Augani",
        "followers_url": "https://api.github.com/users/Augani/followers",
        "following_url": "https://api.github.com/users/Augani/following{/other_user}",
        "gists_url": "https://api.github.com/users/Augani/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Augani/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Augani/subscriptions",
        "organizations_url": "https://api.github.com/users/Augani/orgs",
        "repos_url": "https://api.github.com/users/Augani/repos",
        "events_url": "https://api.github.com/users/Augani/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Augani/received_events",
        "type": "User",
        "site_admin": false
    },
    "html_url": "https://github.com/Augani/hacker",
    "description": "hacker rank react test",
    "fork": false,
    "url": "https://api.github.com/repos/Augani/hacker",
    "forks_url": "https://api.github.com/repos/Augani/hacker/forks",
    "keys_url": "https://api.github.com/repos/Augani/hacker/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Augani/hacker/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Augani/hacker/teams",
    "hooks_url": "https://api.github.com/repos/Augani/hacker/hooks",
    "issue_events_url": "https://api.github.com/repos/Augani/hacker/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Augani/hacker/events",
    "assignees_url": "https://api.github.com/repos/Augani/hacker/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Augani/hacker/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Augani/hacker/tags",
    "blobs_url": "https://api.github.com/repos/Augani/hacker/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Augani/hacker/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Augani/hacker/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Augani/hacker/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Augani/hacker/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Augani/hacker/languages",
    "stargazers_url": "https://api.github.com/repos/Augani/hacker/stargazers",
    "contributors_url": "https://api.github.com/repos/Augani/hacker/contributors",
    "subscribers_url": "https://api.github.com/repos/Augani/hacker/subscribers",
    "subscription_url": "https://api.github.com/repos/Augani/hacker/subscription",
    "commits_url": "https://api.github.com/repos/Augani/hacker/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Augani/hacker/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Augani/hacker/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Augani/hacker/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Augani/hacker/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Augani/hacker/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Augani/hacker/merges",
    "archive_url": "https://api.github.com/repos/Augani/hacker/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Augani/hacker/downloads",
    "issues_url": "https://api.github.com/repos/Augani/hacker/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Augani/hacker/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Augani/hacker/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Augani/hacker/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Augani/hacker/labels{/name}",
    "releases_url": "https://api.github.com/repos/Augani/hacker/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Augani/hacker/deployments",
    "created_at": "2020-08-25T09:24:21Z",
    "updated_at": "2021-02-03T08:37:24Z",
    "pushed_at": "2020-08-25T09:25:33Z",
    "git_url": "git://github.com/Augani/hacker.git",
    "ssh_url": "git@github.com:Augani/hacker.git",
    "clone_url": "https://github.com/Augani/hacker.git",
    "svn_url": "https://github.com/Augani/hacker",
    "homepage": null,
    "size": 179,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master",
    "temp_clone_token": null,
    "network_count": 1,
    "subscribers_count": 1
},
contributors: [
  {
      "login": "Augani",
      "id": 13237525,
      "node_id": "MDQ6VXNlcjEzMjM3NTI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/13237525?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Augani",
      "html_url": "https://github.com/Augani",
      "followers_url": "https://api.github.com/users/Augani/followers",
      "following_url": "https://api.github.com/users/Augani/following{/other_user}",
      "gists_url": "https://api.github.com/users/Augani/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Augani/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Augani/subscriptions",
      "organizations_url": "https://api.github.com/users/Augani/orgs",
      "repos_url": "https://api.github.com/users/Augani/repos",
      "events_url": "https://api.github.com/users/Augani/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Augani/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 2
  }
]
};

